CREATE TABLE IF NOT EXISTS "STATUS" (
	"player_id" INTEGER,
	"Name" TEXT,
	"STR" INTEGER NOT NULL,
	"DEX" INTEGER NOT NULL,
	"DEF" INTEGER NOT NULL,
	"INT" INTEGER NOT NULL,
	"SP" INTEGER NOT NULL,
	"MP" INTEGER NOT NULL,
	PRIMARY KEY("player_id")
);

CREATE TABLE IF NOT EXISTS "Enemy_status" (
	"id_enemy" INTEGER,
	"Name" TEXT,
	"STR" INTEGER NOT NULL,
	"DEX" INTEGER NOT NULL,
	"DEF" INTEGER NOT NULL,
	"INT" INTEGER NOT NULL,
	"SP" INTEGER NOT NULL,
	"MP" INTEGER NOT NULL,
	PRIMARY KEY("id_enemy")
);

CREATE TABLE IF NOT EXISTS "NPC_status" (
	"id_npc" NUMERIC,
	"Name" TEXT,
	"STR" INTEGER NOT NULL,
	"DEX" INTEGER NOT NULL,
	"DEF" INTEGER NOT NULL,
	"INT" INTEGER NOT NULL,
	"SP" INTEGER NOT NULL,
	"MP" INTEGER NOT NULL,
	PRIMARY KEY("id_npc")
);
